plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}


tasks.named('wrapper', Wrapper).configure {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    mavenCentral()

    flatDir {
        dirs("libs")
    }

    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        url "https://harleyoconnor.com/maven"
    }


}

base {
//    archivesName = mod_id
    version = "${minecraft_version}-neoforge-${mod_version}"
    group = "${mod_group_id}" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
    archivesName = mod_name_s
}

// Mojang ships Java 21 to end users starting in 1.20.5, so mods should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager
sourceSets {
    onlyMain {
    }
}
// Default run configurations.
// These can be tweaked, removed, or duplicated as needed.
neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        server {
            server()
            programArgument '--nogui'
            gameDirectory = project.file('runs/server')
        }

        data {
            serverData()
            systemProperty 'eclipticseasons.runs.runData', 'true'
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}



// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }
sourceSets.main.resources { srcDir 'src/generated/server_resources' }

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}


dependencies {
    // Specify the version of Minecraft to use.
    // Depending on the plugin applied there are several options. We will assume you applied the userdev plugin as shown above.
    // The group for userdev is net.neoforged, the module name is neoforge, and the version is the same as the neoforge version.
    // You can however also use the vanilla plugin (net.neoforged.gradle.vanilla) to use a version of Minecraft without the neoforge loader.
    // And its provides the option to then use net.minecraft as the group, and one of; client, server or joined as the module name, plus the game version as version.
    // For all intends and purposes: You can treat this dependency as if it is a normal library you would use.

    // others
    // https://mvnrepository.com/artifact/org.projectlombok/lombok
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    implementation "curse.maven:ecliptic-seasons-1118306:8553646"

    implementation "maven.modrinth:dynamictrees:1.8.0-BETA04"

    implementation ("maven.modrinth:kiwi:26.0.17+neoforge")
    implementation ("maven.modrinth:lychee:26.0.4+neoforge")
    implementation ("maven.modrinth:fruitful-fun:26.0.10+fabric")
//


//    onlyMainRuntimeOnly ("curse.maven:cc-tweaked-282001:5118388")
//    runtimeOnly ("curse.maven:crafttweaker-239197:4277433")

    onlyMainRuntimeOnly "maven.modrinth:sodium:mc26.1.2-0.8.12-neoforge"
    onlyMainRuntimeOnly "maven.modrinth:iris:1.10.9+26.1-neoforge"
    onlyMainRuntimeOnly "curse.maven:jade-324717:7817285"

    println("----Scan onlyMainRuntimeOnly libs begin----")
    fileTree(dir: 'libs', include: ['*.jar']).each { File file ->
        def fileName = file.name
        println(fileName.substring(0, fileName.indexOf("-")) + "," + fileName.substring(fileName.indexOf("-") + 1, fileName.indexOf(".jar")))
        onlyMainRuntimeOnly(name: fileName.substring(0, fileName.indexOf(".jar")),
                group: 'libs',
                version: fileName.substring(0, fileName.indexOf(".jar")))
    }
    println("----Scan onlyMainRuntimeOnly libs end----")

}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.register('deleteCache') {
    delete 'src/generated/resources/.cache'
    delete 'src/generated/server_resources/.cache'
}

jar.dependsOn deleteCache

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

allprojects {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xmaxerrs" << "1000000"
    }
}